### ISSUE TITLE
LinearAverage_2 is missing

### ISSUE THREAD

**Issue by hosseinshn** [VisionLearningGroup/CDS#1]
Hello, 

`lib` directory is not included in the repository, particularly `LinearAverage_2` which is essential for running CDS is missing. I checked the Instance Discrimination repository where a `lib` directory exists but still there was no sign of `LinearAverage_2`. 

Please add that to the repository. 

Thank you.

**Comment by donhk1011** [comment]
Thanks for the checking! I updated the repo. 
Please let me know again if you have other concerns.
